# Basic Python

## 1. Split this string

In [ ]:
s = "Hi i am Harish"

In [ ]:
print(s.split(" "))

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Jupiter"
diameter = 153267

In [4]:
print("The diameter of {0} is {1} kilometers.".format(planet,diameter))

The diameter of Jupiter is 153267 kilometers.

## 3. In this nest dictionary grab the word "harish"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'harish']}]}]}

In [6]:
print(d["k1"][3]["tricky"][3]["target"][3])

harish

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [9]:
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 10 to 50

In [12]:
print(np.arange(10,50,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3, 4]), b = np.array([5, 6, 7, 8])

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6 7 8]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd

In [15]:
data=[["Harish","leader"],["Akash","Member"],["Vignesh","Member"],["Pavitharan","Member"]]
print(pd.DataFrame(data,columns=["Name","Roll"]))

         Name    Roll
0      Harish  leader
1       Akash  Member
2     Vignesh  Member
3  Pavitharan  Member

## 9. Generate the series of dates from 1st Feb, 2024 to 1st Mar, 2024

In [16]:
from datetime import datetime

date=pd.date_range(start="2024-02-01",end="2024-03-01")
print(pd.Series(date))

0    2024-02-01
1    2024-02-02
2    2024-02-03
3    2024-02-04
4    2024-02-05
5    2024-02-06
6    2024-02-07
7    2024-02-08
8    2024-02-09
9    2024-02-10
10   2024-02-11
11   2024-02-12
12   2024-02-13
13   2024-02-14
14   2024-02-15
15   2024-02-16
16   2024-02-17
17   2024-02-18
18   2024-02-19
19   2024-02-20
20   2024-02-21
21   2024-02-22
22   2024-02-23
23   2024-02-24
24   2024-02-25
25   2024-02-26
26   2024-02-27
27   2024-02-28
28   2024-02-29
29   2024-03-01
dtype: datetime64[ns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [33]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [37]:
pd.DataFrame(lists,columns=["No.""Name","ID"])

   No. Name  ID
0    1  aaa  22
1    2  bbb  25
2    3  ccc  24